#### Creating a numpy array

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [6]:
print(type(a))

<class 'numpy.ndarray'>


##### 2D and 3D array

In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
c = np.array([[[1,2,3],[3,4,5]],[[4,5,6],[6,7,8]]])
print(c)

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [6 7 8]]]


#### dtype

In [10]:
np.array([1,2,4],dtype = float)


array([1., 2., 4.])

In [12]:
np.array([1,0,4],dtype = bool)

array([ True, False,  True])

### arange

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
#with reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3,4))

array([[0.61665305, 0.47202   , 0.29164764, 0.55816816],
       [0.97565042, 0.78045236, 0.79574773, 0.38257283],
       [0.25506609, 0.22165789, 0.99375975, 0.60091522]])

In [ ]:
np.linspace(-10,10,10)#generates linealy seperable (which have equal difference) points in a given interval 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [26]:
#np.identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

## Array attributes

In [27]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [32]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
#ndim
a1.ndim

1

In [29]:
a2.ndim

2

In [30]:
a3.ndim

3

In [31]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [33]:
#size
print(a2.size)

12


In [37]:
#itemsize
a1.itemsize

4

In [38]:
a2.itemsize

8

In [39]:
a3.itemsize

4

In [40]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing datatype

In [41]:
#astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

### Array operations

In [45]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [48]:
#scalar operations

#arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [50]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
# vector operations
#arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [53]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [55]:
a1= np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 1., 12., 37.],
       [11., 16., 79.],
       [12.,  8., 88.]])

In [56]:
np.max(a1)

88.0

In [57]:
np.min(a1)

1.0

In [58]:
np.sum(a1)

264.0

In [59]:
np.product(a1)

52152680448.0

In [61]:
#min/max for any particular row
np.max(a1,axis = 0)# 1 -> row , 0 -> col

array([12., 16., 88.])

In [62]:
np.mean(a1)

29.333333333333332

In [63]:
np.median(a1, axis = 1)

array([12., 16., 12.])

In [64]:
np.var(a1 , axis = 1)

array([ 226.88888889,  957.55555556, 1354.66666667])

In [65]:
#trignometric 
np.sin(a1)

array([[ 0.84147098, -0.53657292, -0.64353813],
       [-0.99999021, -0.28790332, -0.44411267],
       [-0.53657292,  0.98935825,  0.0353983 ]])

In [66]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### INdexing and slicing

In [67]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [68]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a1[-1]

9

In [70]:
a1[4]

4

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[1,2]

6

In [73]:
a2[2,3]

11

In [74]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
a3[1,0,1]

5

In [76]:
a3[0,1,0]

2

In [77]:
a3[0,0,0]

0

In [78]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2[0,:]#for 1 st row

array([0, 1, 2, 3])

In [ ]:
a2[:,2]# for 3rd column

array([ 2,  6, 10])

In [81]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [82]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [83]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [84]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [86]:
a3 = np.arange(27).reshape(3,3,3)

In [87]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [91]:
a3[0,1:2,:]

array([[3, 4, 5]])

In [92]:
a3[1,2,1]

16

In [93]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [94]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [95]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [97]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [98]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [99]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshaping

In [100]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [101]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [102]:
#for making 1D array
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [116]:
#horizontal stacking
a4 = np.arange(12).reshape(4,3)
a5 = np.arange(12,24).reshape(4,3)
a5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [117]:
a4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [118]:
np.stack((a4,a5))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### Splitting

In [120]:
np.vsplit(a5,2)

[array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]