In [1]:
import numpy as np

### np.sort

In [2]:
a = np.random.randint(1,100,15)
a

array([49, 34, 51, 21, 82,  2, 32, 72, 24, 75,  5, 54, 85, 43, 11])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91, 50, 87, 59],
       [93, 77, 92, 94],
       [40, 14, 60, 69],
       [89, 55, 70, 41],
       [69, 74, 44,  2],
       [85, 42, 50,  7]])

In [5]:
np.sort(a)

array([ 2,  5, 11, 21, 24, 32, 34, 43, 49, 51, 54, 72, 75, 82, 85])

In [7]:
np.sort(b ,axis =0)

array([[40, 14, 44,  2],
       [69, 42, 50,  7],
       [85, 50, 60, 41],
       [89, 55, 70, 59],
       [91, 74, 87, 69],
       [93, 77, 92, 94]])

In [8]:
 # to sort reverse
np.sort(a)[::-1]

array([85, 82, 75, 72, 54, 51, 49, 43, 34, 32, 24, 21, 11,  5,  2])

### append

In [9]:
np.append(a,200)

array([ 49,  34,  51,  21,  82,   2,  32,  72,  24,  75,   5,  54,  85,
        43,  11, 200])

In [10]:
np.append(b,np.ones((b.shape[0] ,1)),axis = 1)

array([[91., 50., 87., 59.,  1.],
       [93., 77., 92., 94.,  1.],
       [40., 14., 60., 69.,  1.],
       [89., 55., 70., 41.,  1.],
       [69., 74., 44.,  2.,  1.],
       [85., 42., 50.,  7.,  1.]])

### np.concatenate

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [15]:
e = np.array([1,2,2,5,2,54,6,3,45,2,5,3,23,52,5,23,2])
np.unique(e)

array([ 1,  2,  3,  5,  6, 23, 45, 52, 54])

In [17]:
np.expand_dims(a , axis = 1)  

array([[49],
       [34],
       [51],
       [21],
       [82],
       [ 2],
       [32],
       [72],
       [24],
       [75],
       [ 5],
       [54],
       [85],
       [43],
       [11]])

### np.where

In [18]:
a

array([49, 34, 51, 21, 82,  2, 32, 72, 24, 75,  5, 54, 85, 43, 11])

In [ ]:
np.where(a>50) # gives index position based on condition

(array([ 2,  4,  7,  9, 11, 12], dtype=int64),)

In [ ]:
np.where(a>50 ,0 , a)#np.where(condition ,true , false)

array([49, 34,  0, 21,  0,  2, 32,  0, 24,  0,  5,  0,  0, 43, 11])

### np.argmax

In [21]:
np.argmax(a)

12

In [24]:
b

array([[91, 50, 87, 59],
       [93, 77, 92, 94],
       [40, 14, 60, 69],
       [89, 55, 70, 41],
       [69, 74, 44,  2],
       [85, 42, 50,  7]])

In [23]:
np.argmax(b,axis = 1)

array([0, 3, 3, 0, 1, 0], dtype=int64)

In [25]:
np.argmin(a)

5

### np.cumsum

In [27]:
np.cumsum(a)

array([ 49,  83, 134, 155, 237, 239, 271, 343, 367, 442, 447, 501, 586,
       629, 640])

In [26]:
np.cumsum(b)

array([  91,  141,  228,  287,  380,  457,  549,  643,  683,  697,  757,
        826,  915,  970, 1040, 1081, 1150, 1224, 1268, 1270, 1355, 1397,
       1447, 1454])

In [28]:
np.cumprod(a)

array([        49,       1666,      84966,    1784286,  146311452,
        292622904,  773998336, -106694656, 1734295552, 1223147520,
       1820770304, -462651392, -670662656, 1226276864,  604143616])

### np.percentile

In [31]:
a

array([49, 34, 51, 21, 82,  2, 32, 72, 24, 75,  5, 54, 85, 43, 11])

In [32]:
np.percentile(a,75)

63.0

### np.histogram

In [33]:
a

array([49, 34, 51, 21, 82,  2, 32, 72, 24, 75,  5, 54, 85, 43, 11])

In [34]:
np.histogram(a,bins = [0,10 ,20 ,30 ,40 ,50 ,60 ,70 ,80,90,100])

(array([2, 1, 2, 2, 2, 2, 0, 2, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

### np.isin

In [35]:
items = [39,49,32,0,13,32,54]
a[np.isin(a,items)]

array([49, 32, 54])

### np.flip

In [37]:
np.flip(a)

array([11, 43, 85, 54,  5, 75, 24, 72, 32,  2, 82, 21, 51, 34, 49])

In [38]:
np.flip(b,axis = 1)

array([[59, 87, 50, 91],
       [94, 92, 77, 93],
       [69, 60, 14, 40],
       [41, 70, 55, 89],
       [ 2, 44, 74, 69],
       [ 7, 50, 42, 85]])

### np.put

In [39]:
# can replace specific elements of an array with given values of array
np.put(a , [0,1] , [110,530])

In [40]:
a

array([110, 530,  51,  21,  82,   2,  32,  72,  24,  75,   5,  54,  85,
        43,  11])

### np.delete

In [41]:
# returns a new array with deletion of subarray

In [42]:
np.delete(a , [0,2,4])

array([530,  21,   2,  32,  72,  24,  75,   5,  54,  85,  43,  11])

### Set functions

In [43]:
m= np.array([1,2,3,4,5])
n= np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
np.intersect1d(m,n)

array([3, 4, 5])

In [45]:
np.setdiff1d(n,m)

array([6, 7])

In [46]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [47]:
np.in1d(m,1)

array([ True, False, False, False, False])

### np.clip

In [49]:
a

array([110, 530,  51,  21,  82,   2,  32,  72,  24,  75,   5,  54,  85,
        43,  11])

In [48]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 51, 25, 75, 25, 32, 72, 25, 75, 25, 54, 75, 43, 25])